export const majors = ["Computer Science",
    "Computer Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Biomedical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Environmental Engineering",
    "Industrial Engineering",
    "Materials Engineering",
    "Aerospace Engineering",
    "Agricultural and Biological Engineering",
    "Architectural Engineering",
    "Bioengineering",
    "Engineering Physics",
    "Engineering Science",
    "Engineering Systems and Design",
    "Geological Engineering",
    "Management Science and Engineering",
    "Manufacturing Engineering",
    "Marine Engineering",
    "Nuclear Engineering",
    "Ocean Engineering",
    "Operations Research Engineering",
    "Petroleum Engineering",
    "Software Engineering",
    "Systems Engineering",
    "Other Engineering",
    "Mathematics",
    "Statistics",
    "Physics",
    "Chemistry",
    "Biology",
    "Biochemistry",
    "Neuroscience",
    "Economics",
    "Psychology",
    "Political Science",
    "Philosophy",
    "Linguistics",
    "History",
    "English",
    "Anthropology",
    "Sociology",
    "Geography",
    "Communication",
    "Architecture",
    "Urban Studies",
    "Other Humanities",
    "Accounting",
    "Business Administration",
    "Finance",
    "Marketing",
    "Management",
    "Entrepreneurship",
    "Hospitality Management",
    "Human Resources",
    "International Business",
    "Real Estate",
    "Other Business",
    "Agriculture",
    "Animal Science",
    "Food Science",
    "Forestry",
    "Natural Resources",
    "Nutrition",
    "Plant Science",
    "Veterinary Medicine",
    "Other Agriculture",
    "Art",
    "Music",
    "Design",
    "Film",
    "Theatre",
    "Other Arts",
    "Other"]