create schema if not exists "app_auth";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION app_auth.check_duplicate_email()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
  IF EXISTS (SELECT 1 FROM auth.users WHERE email = NEW.email) THEN
    raise exception 'Email is already registered by someone else.';
  END IF;
  
  RETURN NEW;
END;
  $function$
;

CREATE OR REPLACE FUNCTION app_auth.check_duplicate_email2()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
  IF EXISTS (SELECT 1 FROM auth.users WHERE email = NEW.email) THEN
    raise exception 'Email is already registered by someone else.';
  END IF;

  RETURN NEW;
END;
  $function$
;

CREATE OR REPLACE FUNCTION app_auth.check_duplicate_email3()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  IF EXISTS(SELECT 1 FROM auth.users WHERE email = NEW.email) then
    RAISE EXCEPTION 'Email is already being used by someone else';
  END IF;
  RETURN NEW;
END;$function$
;


create table "public"."team_members" (
    "id" uuid not null,
    "team_id" bigint,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."team_members" enable row level security;

create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "leader" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "invites" uuid[] default '{}'::uuid[],
    "team_name" text not null,
    "open_invite" boolean not null default false
);


alter table "public"."teams" enable row level security;

CREATE UNIQUE INDEX team_members_pkey ON public.team_members USING btree (id);

CREATE UNIQUE INDEX teams_id_key ON public.teams USING btree (id);

CREATE UNIQUE INDEX teams_leader_key ON public.teams USING btree (leader);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX teams_team_name_key ON public.teams USING btree (team_name);

alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."team_members" add constraint "team_members_id_fkey" FOREIGN KEY (id) REFERENCES applications(applicant_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."team_members" validate constraint "team_members_id_fkey";

alter table "public"."team_members" add constraint "team_members_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."team_members" validate constraint "team_members_team_id_fkey";

alter table "public"."teams" add constraint "teams_id_key" UNIQUE using index "teams_id_key";

alter table "public"."teams" add constraint "teams_leader_fkey" FOREIGN KEY (leader) REFERENCES applications(applicant_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."teams" validate constraint "teams_leader_fkey";

alter table "public"."teams" add constraint "teams_leader_key" UNIQUE using index "teams_leader_key";

alter table "public"."teams" add constraint "teams_open_invite_check" CHECK ((open_invite = ANY (ARRAY[true, false]))) not valid;

alter table "public"."teams" validate constraint "teams_open_invite_check";

alter table "public"."teams" add constraint "teams_team_name_check" CHECK ((length(team_name) < 28)) not valid;

alter table "public"."teams" validate constraint "teams_team_name_check";

alter table "public"."teams" add constraint "teams_team_name_key" UNIQUE using index "teams_team_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.can_join_team(target_team_id bigint, user_uuid uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$select
    (
      target_team_id is null
      and not exists (
        select 1 from public.teams
        where leader = user_uuid
          and id is distinct from target_team_id
      )
    )
    or
    (
      exists (
        select 1
        from public.teams t
        where t.id = target_team_id
          and (user_uuid = any(t.invites) or t.open_invite = true)
      )
      and (select count(*) from public.team_members where team_id = target_team_id) < 4
      and not exists (
        select 1 from public.teams
        where leader = user_uuid
          and id <> target_team_id
      )
    );$function$
;

CREATE OR REPLACE FUNCTION public.get_team_with_members(team_id_param bigint)
 RETURNS SETOF team_with_members
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select * from public.team_with_members
  where auth.uid() is not null
    AND EXISTS (SELECT 1 FROM applications where applicant_id = auth.uid()) 
    AND (team_id_param is NULL OR team_with_members.id = team_id_param);
$function$
;

CREATE OR REPLACE FUNCTION public.kick_team_member(target_team_member uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
  caller_user_id uuid := NULL;
  member_team_id int;
  team_leader uuid;
BEGIN
  SET search_path = pg_catalog, trusted_schema;
  -- Safely try to get auth.uid() as uuid; if invalid or missing, treat as NULL
  BEGIN
    caller_user_id := auth.uid()::uuid;
  EXCEPTION WHEN others THEN
    caller_user_id := NULL;
  END;

  IF caller_user_id IS NULL THEN
    RAISE EXCEPTION 'Unauthorized: no authenticated user';
  END IF;

  IF caller_user_id = target_team_member THEN
    RAISE EXCEPTION 'Invalid operation: You cannot kick yourself.';
  END IF;

  -- Get the target member's current team
  SELECT team_id
  INTO member_team_id
  FROM public.team_members
  WHERE id = target_team_member;

  IF member_team_id IS NULL THEN
    RAISE EXCEPTION 'Invalid operation: target member is not assigned to a team';
  END IF;

  -- Lookup the leader for that team
  SELECT leader::uuid
  INTO team_leader
  FROM public.teams
  WHERE id = member_team_id;

  IF team_leader IS NULL THEN
    -- this shoulnd't happen
    RAISE EXCEPTION 'Invalid operation: team has no leader';
  END IF;

  -- Ensure caller is the team leader
  IF caller_user_id <> team_leader THEN
    RAISE EXCEPTION 'Unauthorized: only the team leader may remove a member';
  END IF;

  -- All checks passed — perform the removal
  UPDATE public.team_members
  SET team_id = NULL
  WHERE id = target_team_member;

  RETURN;
END;$function$
;

create or replace view "public"."members_no_group" as  SELECT DISTINCT ON (m.id) m.id,
    a.full_name,
    a.email,
    a.university,
    m.created_at
   FROM (team_members m
     LEFT JOIN applications a ON ((a.applicant_id = m.id)))
  WHERE (m.team_id IS NULL)
  ORDER BY m.id, a.created_at DESC;


CREATE OR REPLACE FUNCTION public.team_insert_add_leader()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
  -- Only proceed if leader is provided
  IF NEW.leader IS NULL THEN
    RETURN NEW;
  END IF;

  -- If leader already has a team_members row, update it to new team_id
  IF EXISTS (SELECT 1 FROM public.team_members tm WHERE tm.id = NEW.leader) THEN
    UPDATE public.team_members
    SET team_id = NEW.id,
        created_at = now()
    WHERE id = NEW.leader;
  ELSE
    INSERT INTO public.team_members (id, team_id, created_at)
    VALUES (NEW.leader, NEW.id, now());
  END IF;

  RETURN NEW;
END;
$function$
;

create or replace view "public"."team_with_members" as  SELECT COALESCE(t.id, ('-1'::integer)::bigint) AS id,
    COALESCE(t.team_name, 'Unassigned'::text) AS team_name,
    t.leader,
    COALESCE(t.invites, '{}'::uuid[]) AS invites,
    COALESCE(t.open_invite, false) AS open_invite,
    array_agg(json_build_object('member_id', m.id, 'created_at', m.created_at, 'full_name', a.full_name, 'email', a.email, 'university', a.university) ORDER BY m.created_at) AS members,
    t.created_at
   FROM ((team_members m
     LEFT JOIN teams t ON ((t.id = m.team_id)))
     LEFT JOIN applications a ON ((a.applicant_id = m.id)))
  GROUP BY COALESCE(t.id, ('-1'::integer)::bigint), COALESCE(t.team_name, 'Unassigned'::text), t.leader, t.invites, COALESCE(t.open_invite, false), t.created_at;


CREATE OR REPLACE FUNCTION public.check_user_domain()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN

  PERFORM set_config('search_path', 'public', false);
  IF NEW.email NOT LIKE '%\.edu' THEN
    raise exception 'Please use your University email address ending in `.edu`';
  END IF;

  RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.count_applicants()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$BEGIN
  RETURN COUNT(applicant_id) FROM public.applications;
END;$function$
;

CREATE OR REPLACE FUNCTION public.count_users()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
IF not public.is_admin(auth.uid()) THEN
  RAISE EXCEPTION 'fuc k off';  
END IF;
  RETURN
    COUNT(email)
  from
    auth.users;

END;$function$
;

CREATE OR REPLACE FUNCTION public.get_value(key_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$DECLARE
  result TEXT;
BEGIN
  EXECUTE 'select value from public.kv where key = $1' INTO result USING key_id;
  RETURN result;
END;$function$
;

grant delete on table "public"."team_members" to "anon";

grant insert on table "public"."team_members" to "anon";

grant references on table "public"."team_members" to "anon";

grant select on table "public"."team_members" to "anon";

grant trigger on table "public"."team_members" to "anon";

grant truncate on table "public"."team_members" to "anon";

grant update on table "public"."team_members" to "anon";

grant delete on table "public"."team_members" to "authenticated";

grant insert on table "public"."team_members" to "authenticated";

grant references on table "public"."team_members" to "authenticated";

grant select on table "public"."team_members" to "authenticated";

grant trigger on table "public"."team_members" to "authenticated";

grant truncate on table "public"."team_members" to "authenticated";

grant update on table "public"."team_members" to "authenticated";

grant delete on table "public"."team_members" to "service_role";

grant insert on table "public"."team_members" to "service_role";

grant references on table "public"."team_members" to "service_role";

grant select on table "public"."team_members" to "service_role";

grant trigger on table "public"."team_members" to "service_role";

grant truncate on table "public"."team_members" to "service_role";

grant update on table "public"."team_members" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

create policy "Enable delete for users based on user_id"
on "public"."team_members"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = id));


create policy "team_members_insert_policy"
on "public"."team_members"
as permissive
for insert
to authenticated
with check (((can_join_team(team_id, auth.uid()) OR (team_id IS NULL)) AND (id = auth.uid()) AND (NOT (EXISTS ( SELECT teams.leader
   FROM teams
  WHERE (teams.leader = auth.uid()))))));


create policy "team_members_update_policy"
on "public"."team_members"
as permissive
for update
to authenticated
using ((id = auth.uid()))
with check (((can_join_team(team_id, auth.uid()) OR (team_id IS NULL)) AND (id = auth.uid())));


create policy "users who have an app can see all"
on "public"."team_members"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT applications.applicant_id
   FROM applications
  WHERE (applications.applicant_id = auth.uid()))));


create policy "Enable read access for all users"
on "public"."teams"
as permissive
for select
to authenticated
using (true);


create policy "teams_delete"
on "public"."teams"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = leader));


create policy "teams_insert"
on "public"."teams"
as permissive
for insert
to authenticated
with check (((leader = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1
   FROM status
  WHERE (((status.applicant_id = teams.leader) AND (status.status <> 'rejected'::text)) OR (status.status <> 'cancelled'::text))))));


create policy "teams_update"
on "public"."teams"
as permissive
for update
to authenticated
using (true)
with check (( SELECT (auth.uid() = teams.leader)));


CREATE TRIGGER add_leader_to_team_members AFTER INSERT ON public.teams FOR EACH ROW EXECUTE FUNCTION team_insert_add_leader();


